# Generated by Django 4.0.6 on 2024-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hero', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mana_cost', models.CharField(max_length=255)),
                ('cooldown', models.CharField(max_length=255)),
                ('ability_list', models.TextField()),
            ],
            options={
                'db_table': 'dota_2_abilities',
            },
        ),
    ]
